GRANT USAGE ON SCHEMA labmanager TO service_role;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA labmanager TO service_role;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA labmanager TO service_role;

GRANT USAGE ON TYPE labmanager.user_role TO service_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA labmanager
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO service_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA labmanager
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO service_role;
